import jsPDF from "jspdf";
import "jspdf-autotable";

export interface Itinerary {
  destination: string;
  summary: string;
  totalBudget: string;
  dailyBudget: string;
  bestTimeToVisit?: string;
  currency?: string;
  tips?: string[];
  days: {
    day: number;
    theme: string;
    activities: {
      time: string;
      activity: string;
      location: string;
      description: string;
      estimatedCost: string;
      tip?: string;
    }[];
    meals: {
      type: string;
      restaurant: string;
      cuisine: string;
      estimatedCost: string;
    }[];
    accommodation?: {
      name: string;
      type: string;
      estimatedCost: string;
    };
  }[];
}

export interface SavedTrip {
  id: string;
  destination: string;
  budget: string;
  days: number;
  savedAt: string;
  itinerary: Itinerary;
}

const STORAGE_KEY = "wanderlust_saved_trips";

export function getSavedTrips(): SavedTrip[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

export function saveTrip(itinerary: Itinerary): SavedTrip {
  const trips = getSavedTrips();
  const trip: SavedTrip = {
    id: crypto.randomUUID(),
    destination: itinerary.destination,
    budget: itinerary.totalBudget,
    days: itinerary.days.length,
    savedAt: new Date().toISOString(),
    itinerary,
  };
  trips.unshift(trip);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(trips));
  return trip;
}

export function deleteTrip(id: string) {
  const trips = getSavedTrips().filter((t) => t.id !== id);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(trips));
}

export function downloadItineraryPDF(itinerary: Itinerary) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(194, 100, 40);
  doc.text(`Trip to ${itinerary.destination}`, pageWidth / 2, y, { align: "center" });
  y += 10;

  // Summary
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const summaryLines = doc.splitTextToSize(itinerary.summary, pageWidth - 40);
  doc.text(summaryLines, pageWidth / 2, y, { align: "center" });
  y += summaryLines.length * 5 + 8;

  // Overview
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text(`Budget: ${itinerary.totalBudget}  |  Daily: ${itinerary.dailyBudget}  |  Duration: ${itinerary.days.length} days`, pageWidth / 2, y, { align: "center" });
  y += 10;

  // Tips
  if (itinerary.tips?.length) {
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.text("Travel Tips", 14, y);
    y += 6;
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    itinerary.tips.forEach((tip) => {
      if (y > 270) { doc.addPage(); y = 20; }
      const lines = doc.splitTextToSize(`• ${tip}`, pageWidth - 28);
      doc.text(lines, 18, y);
      y += lines.length * 4.5 + 2;
    });
    y += 6;
  }

  // Days
  itinerary.days.forEach((day) => {
    if (y > 240) { doc.addPage(); y = 20; }

    // Day header
    doc.setFillColor(224, 130, 50);
    doc.roundedRect(14, y - 4, pageWidth - 28, 10, 2, 2, "F");
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.text(`Day ${day.day}: ${day.theme}`, 18, y + 3);
    y += 14;

    // Activities table
    if (day.activities.length) {
      (doc as any).autoTable({
        startY: y,
        head: [["Time", "Activity", "Location", "Cost"]],
        body: day.activities.map((a) => [a.time, a.activity, a.location, a.estimatedCost]),
        theme: "grid",
        headStyles: { fillColor: [194, 100, 40], fontSize: 8 },
        bodyStyles: { fontSize: 8, textColor: [60, 60, 60] },
        margin: { left: 14, right: 14 },
        tableWidth: "auto",
      });
      y = (doc as any).lastAutoTable.finalY + 6;
    }

    // Meals table
    if (day.meals?.length) {
      if (y > 250) { doc.addPage(); y = 20; }
      (doc as any).autoTable({
        startY: y,
        head: [["Meal", "Restaurant", "Cuisine", "Cost"]],
        body: day.meals.map((m) => [m.type, m.restaurant, m.cuisine, m.estimatedCost]),
        theme: "grid",
        headStyles: { fillColor: [50, 130, 120], fontSize: 8 },
        bodyStyles: { fontSize: 8, textColor: [60, 60, 60] },
        margin: { left: 14, right: 14 },
        tableWidth: "auto",
      });
      y = (doc as any).lastAutoTable.finalY + 4;
    }

    // Accommodation
    if (day.accommodation) {
      if (y > 265) { doc.addPage(); y = 20; }
      doc.setFontSize(8);
      doc.setTextColor(80, 80, 80);
      doc.text(`🏨 ${day.accommodation.name} (${day.accommodation.type}) — ${day.accommodation.estimatedCost}`, 14, y);
      y += 8;
    }

    y += 4;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Wanderlust AI Travel Planner · Prices are estimates", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

  doc.save(`${itinerary.destination.replace(/[^a-zA-Z0-9]/g, "_")}_itinerary.pdf`);
}
